WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\1642594\Обучение\pythonProject\home_works\tests_12_4.py", line 69, in test_run
    runner = Runner(12345)
           ^^^^^^^^^^^^^
  File "C:\Users\1642594\Обучение\pythonProject\home_works\tests_12_4.py", line 12, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\1642594\Обучение\pythonProject\home_works\tests_12_4.py", line 60, in test_walk
    walker = Runner('Jhon', -1)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\1642594\Обучение\pythonProject\home_works\tests_12_4.py", line 17, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
